swagger: "2.0"
info: 
  description: Swagger doc for /api/scc/sensors  
  title: Swagger doc for /api/scc/sensors  
  version: 1.0.0
paths: 
  /api/scc/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  SCC_HSC_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P1V8_C_SENSE: 
=======
                  P1V8_E_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SCC_HSC_VOLT: 
=======
                  IOC_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P1V5_E_SENSE: 
=======
                  P0V9_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  IOC_TEMP: 
=======
                  P1V8_C_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P1V5_C_SENSE: 
=======
                  P3V3_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P0V975_SENSE: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P0V9_SENSE: 
=======
                  SCC_HSC_VOLT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  EXPANDER_TEMP: 
=======
                  P1V5_C_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P1V8_E_SENSE: 
=======
                  SCC_HSC_POWER: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P3V3_SENSE: 
=======
                  EXPANDER_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SCC_HSC_POWER: 
=======
                  P1V5_E_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
=======
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
>>>>>>> facebook/helium
                type: array
                items: 
                  type: string
            