swagger: "2.0"
info: 
  description: Swagger doc for /api  
  title: Swagger doc for /api  
  version: 1.0.0
paths: 
  /api: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
<<<<<<< HEAD
                  version: 
                    type: string
                  Description: 
                    type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
=======
                  Description: 
                    type: string
                  version: 
                    type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
>>>>>>> facebook/helium
                type: array
                items: 
                  type: string
            