swagger: "2.0"
info: 
  description: Swagger doc for /api/server/sensors  
  title: Swagger doc for /api/server/sensors  
  version: 1.0.0
paths: 
  /api/server/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
<<<<<<< HEAD
                  INA230 Power: 
=======
                  SOC DIMMA1 Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC Package Pwr: 
=======
                  VDDR VR Curr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P3V3_MB: 
=======
                  PV_BAT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC DIMMA1 Temp: 
=======
                  PVDDR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC Tjmax: 
=======
                  VCCGBE VR Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  INA230 Voltage: 
=======
                  VCCSCSUS VR Vol: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC DIMMB0 Temp: 
=======
                  SOC Tjmax: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCSCSUS VR Pout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  MB Inlet Temp: 
=======
                  VDDR VR Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCGBE VR Curr: 
=======
                  VCCIN VR Pout: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P5V_STBY_MB: 
=======
                  SOC DIMMA0 Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCGBE VR Pout: 
=======
                  1V05PCH VR Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCGBE VR Vol: 
=======
                  SOC Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCGBE VR Temp: 
=======
                  VDDR VR Vol: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  PCH Temp: 
=======
                  VCCIN VR Curr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCIN VR Temp: 
=======
                  VCCGBE VR Curr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  1V05PCH VR Temp: 
=======
                  VCCGBE VR Pout: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCIN VR Curr: 
=======
                  P3V3_MB: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  1V05PCH VR Vol: 
=======
                  PCH Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCIN VR Pout: 
=======
                  SOC DIMMB0 Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  1V05PCH VR Curr: 
=======
                  P3V3_STBY_MB: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  PV_BAT: 
=======
                  1V05PCH VR Vol: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCSCSUS VR Curr: 
=======
                  SOC Therm Margin: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VDDR VR Vol: 
=======
                  VCCSCSUS VR Curr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCIN VR Vol: 
=======
                  INA230 Voltage: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDR VR Pout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCSCSUS VR Temp: 
=======
                  SOC DIMMB1 Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC Therm Margin: 
=======
                  PVCCGBE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P1V05_PCH: 
=======
                  MB Inlet Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  MB Outlet Temp: 
=======
                  P1V05_PCH: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC DIMMB1 Temp: 
=======
                  MB Outlet Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P3V3_STBY_MB: 
=======
                  VCCSCSUS VR Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  PVDDR: 
=======
                  VCCIN VR Vol: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  PVCCGBE: 
=======
                  VCCGBE VR Vol: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VDDR VR Temp: 
=======
                  1V05PCH VR Pout: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P12V_MB: 
=======
                  INA230 Power: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  1V05PCH VR Pout: 
=======
                  P12V_MB: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VCCSCSUS VR Vol: 
=======
                  P5V_STBY_MB: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC Temp: 
=======
                  SOC Package Pwr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  VDDR VR Curr: 
=======
                  1V05PCH VR Curr: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  SOC DIMMA0 Temp: 
=======
                  VCCIN VR Temp: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
=======
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
>>>>>>> facebook/helium
                type: array
                items: 
                  type: string
            