swagger: "2.0"
info: 
  description: Swagger doc for /api/dpb/sensors  
  title: Swagger doc for /api/dpb/sensors  
  version: 1.0.0
paths: 
  /api/dpb/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
<<<<<<< HEAD
                  DPB_Inlet_Temp_2: 
=======
                  FAN1_FRONT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_14_TEMP: 
=======
                  HDD_21_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_Inlet_Temp_1: 
=======
                  HDD_5_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN2_REAR: 
=======
                  HDD_18_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_10_TEMP: 
=======
                  FAN2_FRONT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_19_TEMP: 
=======
                  FAN3_FRONT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_9_TEMP: 
=======
                  FAN3_REAR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_8_TEMP: 
=======
                  DPB_HSC_VOLT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_6_TEMP: 
=======
                  Airflow: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_15_TEMP: 
=======
                  HDD_2_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_24_TEMP: 
=======
                  DPB_Inlet_Temp_1: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN1_FRONT: 
=======
                  HDD_3_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN4_FRONT: 
=======
                  DPB_Inlet_Temp_2: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_12V_POWER_CLIP: 
=======
                  HDD_12_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P5V_2_SENSE: 
=======
                  HDD_28_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_HSC_CURR: 
=======
                  DPB_12V_CURR_CLIP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN4_REAR: 
=======
                  P5V_2_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_29_TEMP: 
=======
                  HDD_19_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN2_FRONT: 
=======
                  HDD_31_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_12V_CURR_CLIP: 
=======
                  HDD_9_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN1_REAR: 
=======
                  FAN2_REAR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_12_TEMP: 
=======
                  HDD_20_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_35_TEMP: 
=======
                  HDD_13_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  Airflow: 
=======
                  HDD_8_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_11_TEMP: 
=======
                  FAN4_REAR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_7_TEMP: 
=======
                  HDD_16_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_5_TEMP: 
=======
                  HDD_26_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_28_TEMP: 
=======
                  FAN1_REAR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_25_TEMP: 
=======
                  P5V_4_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_P12V_CLIP: 
=======
                  HDD_1_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P5V_4_SENSE: 
=======
                  HDD_34_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_23_TEMP: 
=======
                  HDD_33_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_27_TEMP: 
=======
                  P5V_3_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P5V_1_SENSE: 
=======
                  HDD_22_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_4_TEMP: 
=======
                  DPB_HSC_CURR: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_HSC_VOLT: 
=======
                  P3V3_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_32_TEMP: 
=======
                  DPB_12V_POWER_CLIP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P5V_3_SENSE: 
=======
                  HDD_23_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_20_TEMP: 
=======
                  HDD_35_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_26_TEMP: 
=======
                  HDD_24_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  P3V3_SENSE: 
=======
                  HDD_25_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_34_TEMP: 
=======
                  FAN4_FRONT: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_17_TEMP: 
=======
                  DPB_HSC_POWER: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_31_TEMP: 
=======
                  HDD_7_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  DPB_HSC_POWER: 
=======
                  HDD_14_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_2_TEMP: 
=======
                  HDD_27_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN3_REAR: 
=======
                  HDD_4_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  FAN3_FRONT: 
=======
                  HDD_17_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_1_TEMP: 
=======
                  DPB_P12V_CLIP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_33_TEMP: 
=======
                  HDD_29_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_0_TEMP: 
=======
                  HDD_6_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_13_TEMP: 
=======
                  HDD_30_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_16_TEMP: 
=======
                  HDD_0_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_21_TEMP: 
=======
                  P5V_1_SENSE: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_30_TEMP: 
=======
                  HDD_11_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_18_TEMP: 
=======
                  HDD_32_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_22_TEMP: 
=======
                  HDD_15_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
                  HDD_3_TEMP: 
=======
                  HDD_10_TEMP: 
>>>>>>> facebook/helium
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
<<<<<<< HEAD
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
=======
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
>>>>>>> facebook/helium
                type: array
                items: 
                  type: string
            