swagger: "2.0"
info: 
  description: Swagger doc for /api/spb/sensors  
  title: Swagger doc for /api/spb/sensors  
  version: 1.0.0
paths: 
  /api/spb/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  BMC_SENSOR_FAN0_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN1_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN2_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN3_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN4_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN5_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN6_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN7_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PWM0: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PWM1: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PWM2: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PWM3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_OUTLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_INLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P5V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P3V3_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P1V15_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P1V2_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_P2V5_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_VIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_PIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_EIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_IOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_PEAK_IOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_HSC_PEAK_PIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_MEDUSA_VOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_MEDUSA_VIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_MEDUSA_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_MEDUSA_PWR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_MEDUSA_VDELTA: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PDB_DL_VDELTA: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_PDB_BB_VDELTA: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_CURR_LEAKAGE: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN_IOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_FAN_PWR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_NIC_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_NIC_IOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  BMC_SENSOR_NIC_PWR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            