swagger: "2.0"
info: 
  description: Swagger doc for /api/server1/sensors  
  title: Swagger doc for /api/server1/sensors  
  version: 1.0.0
paths: 
  /api/server1/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: true
                properties: 
                  MB Inlet Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB Outlet Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  FRONT IO Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PCH Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC CPU Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC Therm Margin: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC CPU TjMax: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  CPU Package Pwr: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMA Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMB Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMC Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMD Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMME Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMF Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SSD0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIN VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCSA VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIO VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  3V3_STBY VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_ABC VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_DEF VR Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P12V_STBY Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V_BAT Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_STBY Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P1V05_PCH Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVNN_PCH Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC Input Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIN VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCSA VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIO VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_STBY VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_ABC VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_DEF VR Vol: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC Output Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIN VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCSA VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIO VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_STBY VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_ABC VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_DEF VR Cur: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC Input Pwr: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC Input AvgPwr: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIN VR Pout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCSA VR Pout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VCCIO VR Pout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_STBY VRPout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_ABC VRPout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  VDDQ_DEF VRPout: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            
