swagger: "2.0"
info: 
  description: Swagger doc for /api/sled/mezz  
  title: Swagger doc for /api/sled/mezz  
  version: 1.0.0
paths: 
  /api/sled/mezz: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
<<<<<<< HEAD
=======
              Resources: 
                type: array
                items: 
                  type: string
>>>>>>> facebook/helium
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  Description: 
                    type: string
<<<<<<< HEAD
              Resources: 
                type: array
                items: 
                  type: string
=======
>>>>>>> facebook/helium
              Actions: 
                type: array
                items: 
                  type: string
            