swagger: "2.0"
info: 
  description: Swagger doc for /api/e1s_iocm/sensors  
  title: Swagger doc for /api/e1s_iocm/sensors  
  version: 1.0.0
paths: 
  /api/e1s_iocm/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  E1S_A0_CUR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A1_CUR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A0_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A1_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A0_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A1_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A0_P3V3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  E1S_A1_P3V3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            